/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <LCD.h>
#include <UART.h>
#include <rx_int.h>
#include <tx_int.h>
#include <TX_aliases.h>
#include <TX.h>
#include <RIGHT_PIN_aliases.h>
#include <RIGHT_PIN.h>
#include <LEFT_PIN_aliases.h>
#include <LEFT_PIN.h>
#include <TEST_PIN_aliases.h>
#include <TEST_PIN.h>
#include <MID_PIN_aliases.h>
#include <MID_PIN.h>
#include <DOWN_PIN_aliases.h>
#include <DOWN_PIN.h>
#include <UP_PIN_aliases.h>
#include <UP_PIN.h>
#include <Clock_1.h>
#include <AMux.h>
#include <ADC.h>
#include <ISR.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <ADC_theACLK.h>
#include <ADC_Ext_CP_Clk.h>
#include <ADC_AMux.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
